# Generated by Django 2.2.12 on 2022-08-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220825_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
