# Generated by Django 2.2.12 on 2022-08-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shop_name',
        ),
    ]
