# Generated by Django 2.2.12 on 2022-08-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customuser_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
